name: CI/CD with GHCR and Azure Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io \
            -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/ml-app:${IMAGE_TAG} .

      - name: Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/ml-app:${IMAGE_TAG}

      - name: Update Azure Web App container
        run: |
          az webapp config container set \
            --name ml-cicd-demo \
            --resource-group CloudAI \
            --docker-custom-image-name ghcr.io/${{ secrets.GHCR_USERNAME }}/ml-app:${{ github.sha }} \
            --docker-registry-server-url https://ghcr.io \
            --docker-registry-server-user ${{ secrets.GHCR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.GHCR_TOKEN }}
